### ISSUE TITLE
Unexpected status code 403

### ISSUE THREAD

**Issue by smugvee** [V4NSH4J/discord-inviter-GO#3]
![image](https://user-images.githubusercontent.com/85663797/144339713-e58adecc-0a62-4984-bcce-45fed2e6014b.png)
I've tried using a VPN and also tried different tokens.

**Comment by V4NSH4J** [comment]
Error 403 is Unauthorised. Meaning you're locked/disabled

**Comment by dox-net** [comment]
Oh okay! Thanks!

**Comment by Supremeondc** [comment]
> Error 403 is Unauthorised. Meaning you're locked/disabled

how can I prevent these tokens from getting the locked disabled message? increase delays?
